### ISSUE TITLE
Include GCode.xml & hngc.lang in project?

### ISSUE THREAD

**Issue by TurBoss** [KurtJacobson/hazzy#17]
Can we include this files in the main project? GCode.xml & hngc.lang
just asking 
my installation of linuxcnc is configured to run in place (compiled from sources but not installed)
so I can have hazzy under the home directory

**Comment by KurtJacobson** [comment]
Yes, we can certainly include these files. I need to clean them up a bit and then I will add them. 

There appears to be a bug in GTKsourcview so it does not set the search path correctly (This is what causes that "GtkSourceView-CRITICAL **: ..." error) This means that the lang spec files will have to be put in /usr/share/gtksourceview-3.0/ to work. I'd prefer if gtksourceview could just find them in the Hazzy directory, but Oh well...

**Comment by TurBoss** [comment]
fixed in https://github.com/KurtJacobson/hazzy/pull/23

Thanks
