### ISSUE TITLE
Signal missing Handler 

### ISSUE THREAD

**Issue by TurBoss** [KurtJacobson/hazzy#18]
I found this:

```
/home/turboss/Sources/hazzy/hazzy/modules/touchpads/touchpad.py:47: RuntimeWarning: missing handler 'on_window_focus_out_event'
  self.builder.connect_signals(self)
/home/turboss/Sources/hazzy/hazzy/hazzy.py:139: RuntimeWarning: missing handler 'on_new_folder_clicked'
  self.builder.connect_signals(self)
/home/turboss/Sources/hazzy/hazzy/hazzy.py:139: RuntimeWarning: missing handler 'on_save_clicked'
  self.builder.connect_signals(self)
```
seems that is unimplemented yet :P 

I just opened the issue as reminder

**Comment by KurtJacobson** [comment]
'on_window_focus_out_event' is not longer used so I removed it.
'on_new_folder_clicked' is not implemented yet, but soon to be. (I needed it this morning in the shop)
'on_save_clicked' should have been 'on_save_file_clicked'

Thank you!
