### ISSUE TITLE
use logger instead of prints

### ISSUE THREAD

**Issue by TurBoss** [KurtJacobson/hazzy#19]
this is a reminder for myself

I will change all the prints to use logger instead

https://docs.python.org/2/library/logging.html

**Comment by KurtJacobson** [comment]
That would be excellent, thank you very much!

**Comment by TurBoss** [comment]
some progress are on https://github.com/TurBoss/hazzy/tree/UseLogger/hazzy/modules/customlog

**Comment by KurtJacobson** [comment]
Maybe make the logger singleton?
http://stackoverflow.com/questions/20372669/python-use-the-same-class-instance-in-multiple-modules

**Comment by KurtJacobson** [comment]
Maybe the dialogs should be singleton too.

**Comment by TurBoss** [comment]
I don't understand yet :_D
sadly I forgot to ask my friend...

**Comment by TurBoss** [comment]
https://docs.python.org/2/howto/logging-cookbook.html

I'm checking this...

**Comment by TurBoss** [comment]
"Multiple calls to logging.getLogger('someLogger') return a reference to the same logger object. This is true not only within the same module, but also across modules as long as it is in the same Python interpreter process. It is true for references to the same object; additionally, application code can define and configure a parent logger in one module and create (but not configure) a child logger in a separate module, and all logger calls to the child will pass up to the parent."

**Comment by KurtJacobson** [comment]
So I guess with the standard lib logger you have to pass 'someLogger' between modules at init, just like you have done with your custom logger.

Sorry, I'm at the beach and I don't have a real computer here so I can't play with the code :(

**Comment by TurBoss** [comment]
no worries, have fun :D

**Comment by TurBoss** [comment]
done in https://github.com/KurtJacobson/hazzy/pull/24

**Comment by KurtJacobson** [comment]
@TurBoss I finally was able to come up with a solution to avoid the escape sequences showing up in the log file. See here: https://gist.github.com/KurtJacobson/c87425ad8db411c73c6359933e5db9f9
