### ISSUE TITLE
While running a program, it is possible to change spindle speed and tool

### ISSUE THREAD

**Issue by gmoccapy** [KurtJacobson/hazzy#28]
I played around with you GUI and be sure, I will steel as much as you have stolen from gmoccapy :-)

I like the GUI, but I noted, that while a program is running, you are able to click in the spindle speed entry and set a new value, resulting in locking the screen for a while. Same happen if you click in the tool entry. As I am playing only in sim mode, I am not able to tell you, if that has any influence to the real movement. 

But IMHO you should disable some widgets, while running a program.

I will follow for sure the development from the very nice GUI.

Norbert (gmoccapy)

**Comment by KurtJacobson** [comment]
Thank your Norbert! It is not stealing if you use some of the work you taught your student how to do :-) (and I do consider you my teacher, and a very good one at that!)

Thank you for opening this issue. There are still a lot of bugs like this here and there that I need to work on fixing.

Kurt

**Comment by KurtJacobson** [comment]
Closing since this bug is not longer applicable since porting to GTK3.
