### ISSUE TITLE
Class name should go with first letter in capital

### ISSUE THREAD

**Issue by TurBoss** [KurtJacobson/hazzy#4]
can I rename the classes name to capitals ?

**Comment by KurtJacobson** [comment]
Absolutely, if that is how it is supposed to be! I have no clue what I am doing, only programing experience I have is from a MATLAB course so I am sure there a lot of things that I have done that are less than correct, it would be great if you would tell me what I am doing wrong. Thank you!

**Comment by TurBoss** [comment]
I would like to help in programming too but first ! need to get into the code so I'm fixing the most easy things I am finding in the path.

Thank you this project is awesome.
