### ISSUE TITLE
Review your git commits with some graphical tool

### ISSUE THREAD

**Issue by TurBoss** [KurtJacobson/hazzy#9]
I see my commits go to master but yours stay in a separate ¿"branch"? merge them to master or something

I use gitkraken (not Libre) but there are good libre gui clients out there

Thanks

![captura de pantalla de 2017-04-22 18-00-16](https://cloud.githubusercontent.com/assets/184088/25306015/e5d16d18-2785-11e7-8991-e8ef26326780.png)

**Comment by TurBoss** [comment]
If you have any question please feel free to ask here
or could be my git client :D

**Comment by TurBoss** [comment]
definitively is my client sorry for the confusion
![captura de pantalla de 2017-04-22 18-11-24](https://cloud.githubusercontent.com/assets/184088/25306117/208b97fc-2787-11e7-9607-1fed09732d7a.png)

**Comment by KurtJacobson** [comment]
Thats over my head. git status says I am on master, bit it does look like I am on a different branch on you screen shot. 
I merge my commits by saying "git push origin master" and I merge your pull requests on github. Is that incorrect? 

I need to get a GUI like yours, that would help a lot to see what is going on...

**Comment by KurtJacobson** [comment]
So I am OK?

**Comment by TurBoss** [comment]
yes

and Sorry man i was confused with my client

Thanks

**Comment by KurtJacobson** [comment]
Excellent! You had me scared for a minute there!
